# define the url to online data repository
url<-"https://raw.githubusercontent.com/dschoolmaster/GLSReplyData/main/"

#read in elements generated by GLS simulation

#(1)community composition for each plot from GLS sim
experiment_record<-read.csv(paste0(url,"GraceSimRecord.csv")) 
#(2)Final ecosystem function (F.dat) values from GLS sim
GLS.F.dat<-read.csv(paste0(url,"Fdat.csv"))
#(3)The error added to each ecosystem function value of F.dat from GLS sim
GLS.error<-read.csv(paste0(url,"FdatError.csv"))

#reshape as a vector of errors
U<-c((as.matrix(GLS.error))) 

#reshape GLS results as vector
GLS.result<-c((as.matrix(GLS.F.dat))) 

#trait value of species pool (T)
T_ <- c(1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10) 
n.spp = length(T_)
n.sims <- 10
num.of.plots<-n.spp*n.sims

#create empty vector of functional trait composite for each plot
Q<-rep(NA,num.of.plots)

#create an empty vector of ecosystem function for each plot (F).
F_<-rep(NA,num.of.plots)

#define Intervention matrix to inform experiment (see Figure 2 of main text) 
I_<-matrix(FALSE,nrow=nrow(experiment_record),ncol=ncol(experiment_record))

#fill it with the species selection information from GLS experiment
for(i in 1:(num.of.plots))for(j in 
                              1:n.spp)if(!is.na(experiment_record[i,j]))I_[i,experiment_record[i,j]]<-TRUE

for (k in 1:num.of.plots){# index over of the plots in the experiment
  # calc Q as a function of the traits in plot  
  Q[k]<-sum(unique(T_[I_[k,]])) 
  
  # calc F as Q + error
  F_[k]<-Q[k]+U[k]                       
}

all.equal(F_,GLS.result)

##Part 2: removal of species richness values


#create vector of only unique trait states
T_2<-1:10

#create matrix structure for I_2
I_2<-matrix(FALSE,nrow=nrow(experiment_record),ncol=length(T_2))
# fill it
for(i in 1:num.of.plots)
  I_2[i,
      T_2[
        T_[
          unlist(experiment_record[i,which(!is.na(experiment_record[i,]))])
          ]
        ]
      ]<-T

#create new Q and F vectors

#vector of trait-based composite (Q) for each plot
Q2<-rep(NA,num.of.plots)

#vector of ecosystem function for each plot (F)
F_2<-rep(NA,num.of.plots) 

for (k in 1:num.of.plots){ #index over of the plots in the experiment
  #calc Q2 as a function of the traits in plot
  Q2[k]<-sum(unique(T_2[I_2[k,]]))
  #calc F2 as Q2 + error
  F_2[k]<-Q2[k]+U[k]              
}

all.equal(F_2,GLS.result)
all.equal(Q2,Q)
